version: '3.8'

services:
  dns-server:
    build:
      context: ./ 
      dockerfile: ./bind/Dockerfile
    container_name: dns-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.3
    ports:
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
    restart: always

<<<<<<< HEAD
smtp-server:
  build:
    context: ./
    dockerfile: ./smtp/Dockerfile
  container_name: smtp-server
  networks:
    mail_network:
      ipv4_address: 172.19.0.4
  dns:
    - 172.19.0.3
  environment:
    MAILNAME: smtp.example.local
  ports:
    - "1025:25"
  volumes:
    - ./smtp_aliases:/etc/aliases
    - mail_data:/var/mail      # 共有ボリュームをマウント
    - ./smtp_config/postfix/main.cf:/etc/postfix/main.cf
    - ./smtp_config/postfix/master.cf:/etc/postfix/master.cf
    - ./smtp_config/postfix/virtual:/etc/postfix/virtual
  restart: always
  depends_on:
    - dns-server


  pop3-server:
    build:
      context: ./ 
      dockerfile: ./pop3/Dockerfile
    container_name: pop3-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.7
    ports:
      - "110:110"    # POP3ポート
    volumes:
      - ./etc/dovecot:/etc/dovecot
      - mail_data:/var/mail           # 共有ボリュームをマウント
      - mail_data:/var/log/dovecot    # ログも共有（オプション）
    restart: always
    depends_on:
      - smtp-server
=======
  smtp-server:
    build:
      context: .
      dockerfile: ./smtp/Dockerfile
    container_name: smtp-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.4
    dns:
      - 172.19.0.3
    environment:
      MAILNAME: smtp.example.local
    ports:
      - "1025:25"
      - "110:110"  # POP3ポート追加
    volumes:
      - ./smtp_aliases:/etc/aliases
      - ./dovecot:/etc/dovecot  # Dovecot設定ファイル追加
      - mail_data:/var/mail  # 名前付きボリュームに変更
    restart: always
    depends_on:
      - dns-server
    cap_add:
      - SYSLOG

>>>>>>> temp-branch

  app-server:
    build: ./app-server
    container_name: app-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.5
    dns:
      - 172.19.0.3
    environment:
      SMTP_SERVER: smtp.example.local
    depends_on:
      - dns-server
      - smtp-server
    command: ["sh", "-c", "python3 send_mail.py && tail -f /dev/null"]

  client:
    build: ./client
    container_name: client
    networks:
      mail_network:
        ipv4_address: 172.19.0.6
    dns:
      - 172.19.0.3
    stdin_open: true
    tty: true
    command: sleep infinity

networks:
  mail_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
<<<<<<< HEAD
  mail_data:
=======
  mail_data:
>>>>>>> temp-branch
