version: '3.8'

services:
  dns-server:
    build:
      context: ./ 
      dockerfile: ./bind/Dockerfile
    container_name: dns-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.3
    ports:
      - "53:53/udp"
    volumes:
      - ./bind:/etc/bind
    restart: always

  smtp-server:
    build:
      context: .
      dockerfile: ./smtp/Dockerfile
    container_name: smtp-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.4
    dns:
      - 172.19.0.3
    environment:
      MAILNAME: smtp.example.local
    ports:
      - "1025:25"
      - "110:110"  # POP3ポート追加
    volumes:
      - ./smtp_aliases:/etc/aliases
      - ./dovecot:/etc/dovecot  # Dovecot設定ファイル追加
      - mail_data:/var/mail  # 名前付きボリュームに変更
    restart: always
    depends_on:
      - dns-server
    cap_add:
      - SYSLOG


  app-server:
    build: ./app-server
    container_name: app-server
    networks:
      mail_network:
        ipv4_address: 172.19.0.5
    dns:
      - 172.19.0.3
    environment:
      SMTP_SERVER: smtp.example.local
    depends_on:
      - dns-server
      - smtp-server
    command: ["sh", "-c", "python3 send_mail.py && tail -f /dev/null"]

  client:
    build: ./client
    container_name: client
    networks:
      mail_network:
        ipv4_address: 172.19.0.6
    dns:
      - 172.19.0.3
    stdin_open: true
    tty: true
    command: sleep infinity

networks:
  mail_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  mail_data:
